name: ChatFCoin CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    env:
      GITHUB_ACTION: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.13.2'
              otp: '24.2'
              postgres: '14.1-alpine'

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{matrix.pair.postgres}}
        env:
          POSTGRES_DB: mishka_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            mix.lock
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-
            
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}


      - name: Elixir and Erlang Dependencies
        run: | 
          mix local.hex --force
          mix local.rebar --force
          mix archive.install hex phx_new --force

      - name: Source Compiling
        run: | 
          mix deps.get
          mix deps.update --all
          mix deps.compile
          mix assets.deploy

      - name: Run mix ecto.setup
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{job.services.postgres.ports[5432]}}/chat_f_coin_test
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: mishka_test
          DATABASE_HOST: localhost
        run: |
          mix ecto.drop
          mix ecto.create
          cd apps/mishka_database/
          mix mishka_installer.db.gen.migration
          cd ../..
          mix ecto.migrate

      - name: Run test with temporary information
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{job.services.postgres.ports[5432]}}/chat_f_coin_test
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: mishka_test
          DATABASE_HOST: localhost
        run: |
          mix test --trace
